//
//  ArtistInteractor.swift
//  VIPDemo
//
//  Created by Daniela Dias on 07/10/2016.
//  Copyright (c) 2016 ustwo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit


// MARK: - ArtistInteractorInput

protocol ArtistInteractorInput: ArtistViewControllerOutput {

}


// MARK: - ArtistInteractorOutput

protocol ArtistInteractorOutput {

    func presentArtist(artist: Artist)
}


// MARK: - ArtistInteractor

class ArtistInteractor: ArtistInteractorInput {

    var output: ArtistInteractorOutput!
    var worker: ArtistWorker!


    // MARK: - Business logic

    func fetchArtist() {

        worker = ArtistWorker()

        // TODO: Fetch Artist
    }
}
