//
//  AlbumWorker.swift
//  VIPDemo
//
//  Created by Daniela Dias on 07/10/2016.
//  Copyright (c) 2016 ustwo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit


// MARK: - AlbumWorker

final class AlbumWorker {

    fileprivate var store: AlbumsStoreProtocol


    // MARK: - Initializers

    init(store: AlbumsStoreProtocol = AlbumsAPIStore()) {

        self.store = store
    }


    // MARK: - Business Logic

    func fetchAlbums(artistId: String, completion: @escaping ([Album], Error?) -> ()) {

        store.fetchAlbums(artistId: artistId, completion: completion)
    }
}
