//
//  ArtistWorker.swift
//  VIPDemo
//
//  Created by Daniela Dias on 07/10/2016.
//  Copyright (c) 2016 ustwo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit


// MARK: - ArtistWorker

final class ArtistWorker {


    // MARK: - Business Logic

    func fetchArtist(completion: @escaping (Artist, Error?) -> ()) {

        // TODO
    }
}
